#在以下路径中寻找 boost

set(Boost_ADDITIONAL_VERSIONS "1.50" "1.50.0"  "1.49" "1.49.0" "1.48" "1.48.0" "1.47" "1.47.0" "1.46" "1.46.0" "1.46.1" "1.44" "1.44.0" "1.42" "1.42.0" "1.41.0" "1.41" "1.40.0" "1.40" "1.39.0" "1.39" "1.38.0" "1.38" "1.37.0" "1.37" )
set(Boost_USE_STATIC_LIBS        ON)
set(Boost_USE_MULTITHREADED      ON)
set(Boost_USE_STATIC_RUNTIME    OFF)
find_package(Boost COMPONENTS "date_time" "system" "filesystem" "iostreams" "log_setup" "log" "regex" "unit_test_framework" "zlib" "thread" "context")



#项目结束时候配置
macro( boost_vc80_vc90_vc100 )
	foreach(var ${ARGN})
		string(TOUPPER ${var} var_toupper)
				
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc80\\3" Boost_${var_toupper}_LIBRARY_DEBUG_VC80 ${Boost_${var_toupper}_LIBRARY_DEBUG} )
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc90\\3" Boost_${var_toupper}_LIBRARY_DEBUG_VC90 ${Boost_${var_toupper}_LIBRARY_DEBUG} )
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc100\\3" Boost_${var_toupper}_LIBRARY_DEBUG_VC100 ${Boost_${var_toupper}_LIBRARY_DEBUG} )
		
		
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc80\\3" Boost_${var_toupper}_LIBRARY_RELEASE_VC80 ${Boost_${var_toupper}_LIBRARY_RELEASE} )
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc90\\3" Boost_${var_toupper}_LIBRARY_RELEASE_VC90 ${Boost_${var_toupper}_LIBRARY_RELEASE} )
		string( REGEX REPLACE "(.*-)(vc.0)(-.*)$" "\\1vc100\\3" Boost_${var_toupper}_LIBRARY_RELEASE_VC100 ${Boost_${var_toupper}_LIBRARY_RELEASE} )
	
	endforeach()
endmacro( boost_vc80_vc90_vc100 )

boost_vc80_vc90_vc100("date_time" "system" "filesystem" "iostreams" "log_setup" "log" "regex" "unit_test_framework" "zlib" "thread" "context")

install(FILES 
${Boost_THREAD_LIBRARY_DEBUG_VC100}
${Boost_FILESYSTEM_LIBRARY_DEBUG_VC100}
${Boost_IOSTREAMS_LIBRARY_DEBUG_VC100}
${Boost_LOG_SETUP_LIBRARY_DEBUG_VC100}
${Boost_LOG_LIBRARY_DEBUG_VC100}
${Boost_REGEX_LIBRARY_DEBUG_VC100}
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG_VC100}
${Boost_DATE_TIME_LIBRARY_DEBUG_VC100}
${Boost_SYSTEM_LIBRARY_DEBUG_VC100}
${Boost_ZLIB_LIBRARY_DEBUG_VC100}
${Boost_CONTEXT_LIBRARY_DEBUG_VC100}
DESTINATION vc100/lib/debug/)


install(FILES 
${Boost_THREAD_LIBRARY_RELEASE_VC100} 
${Boost_FILESYSTEM_LIBRARY_RELEASE_VC100} 
${Boost_IOSTREAMS_LIBRARY_RELEASE_VC100} 
${Boost_LOG_SETUP_LIBRARY_RELEASE_VC100} 
${Boost_LOG_LIBRARY_RELEASE_VC100} 
${Boost_REGEX_LIBRARY_RELEASE_VC100} 
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE_VC100} 
${Boost_DATE_TIME_LIBRARY_RELEASE_VC100}
${Boost_SYSTEM_LIBRARY_RELEASE_VC100}
${Boost_ZLIB_LIBRARY_RELEASE_VC100}
${Boost_CONTEXT_LIBRARY_RELEASE_VC100}
DESTINATION vc100/lib/release/)

install(FILES 
${Boost_THREAD_LIBRARY_DEBUG_VC90}
${Boost_FILESYSTEM_LIBRARY_DEBUG_VC90}
${Boost_IOSTREAMS_LIBRARY_DEBUG_VC90}
${Boost_LOG_SETUP_LIBRARY_DEBUG_VC90}
${Boost_LOG_LIBRARY_DEBUG_VC90}
${Boost_REGEX_LIBRARY_DEBUG_VC90}
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG_VC90}
${Boost_DATE_TIME_LIBRARY_DEBUG_VC90}
${Boost_SYSTEM_LIBRARY_DEBUG_VC90}
${Boost_ZLIB_LIBRARY_DEBUG_VC90}
${Boost_CONTEXT_LIBRARY_DEBUG_VC90}
DESTINATION vc90/lib/debug/)

install(FILES 
${Boost_THREAD_LIBRARY_RELEASE_VC90} 
${Boost_FILESYSTEM_LIBRARY_RELEASE_VC90} 
${Boost_IOSTREAMS_LIBRARY_RELEASE_VC90} 
${Boost_LOG_SETUP_LIBRARY_RELEASE_VC90} 
${Boost_LOG_LIBRARY_RELEASE_VC90} 
${Boost_REGEX_LIBRARY_RELEASE_VC90} 
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE_VC90} 
${Boost_DATE_TIME_LIBRARY_RELEASE_VC90} 
${Boost_SYSTEM_LIBRARY_RELEASE_VC90} 
${Boost_ZLIB_LIBRARY_RELEASE_VC90} 
${Boost_CONTEXT_LIBRARY_RELEASE_VC90}
DESTINATION vc90/lib/release/)


install(FILES 
${Boost_THREAD_LIBRARY_DEBUG_VC80}
${Boost_FILESYSTEM_LIBRARY_DEBUG_VC80}
${Boost_IOSTREAMS_LIBRARY_DEBUG_VC80}
${Boost_LOG_SETUP_LIBRARY_DEBUG_VC80}
${Boost_LOG_LIBRARY_DEBUG_VC80}
${Boost_REGEX_LIBRARY_DEBUG_VC80}
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG_VC80}
${Boost_DATE_TIME_LIBRARY_DEBUG_VC80}
${Boost_SYSTEM_LIBRARY_DEBUG_VC80}
${Boost_ZLIB_LIBRARY_DEBUG_VC80}
${Boost_CONTEXT_LIBRARY_DEBUG_VC80}
DESTINATION vc80/lib/debug/)


install(FILES 
${Boost_THREAD_LIBRARY_RELEASE_VC80} 
${Boost_FILESYSTEM_LIBRARY_RELEASE_VC80} 
${Boost_IOSTREAMS_LIBRARY_RELEASE_VC80} 
${Boost_LOG_SETUP_LIBRARY_RELEASE_VC80} 
${Boost_LOG_LIBRARY_RELEASE_VC80} 
${Boost_REGEX_LIBRARY_RELEASE_VC80} 
${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE_VC80} 
${Boost_DATE_TIME_LIBRARY_RELEASE_VC80} 
${Boost_SYSTEM_LIBRARY_RELEASE_VC80} 
${Boost_ZLIB_LIBRARY_RELEASE_VC80} 
${Boost_CONTEXT_LIBRARY_RELEASE_VC80}
DESTINATION vc80/lib/release/)

install(DIRECTORY ${Boost_INCLUDE_DIR}/boost DESTINATION include PATTERN "CVS" EXCLUDE PATTERN ".svn" EXCLUDE )