# settings for Microsoft Visual C++
if(CMAKE_CXX_COMPILER MATCHES cl)
	if(CMAKE_GENERATOR STREQUAL "Visual Studio 8 2005")
		SET(compiler "vc80")
	endif(CMAKE_GENERATOR STREQUAL "Visual Studio 8 2005")
	if(CMAKE_GENERATOR STREQUAL "Visual Studio 9 2008")
		SET(compiler "vc90")
	endif(CMAKE_GENERATOR STREQUAL "Visual Studio 9 2008")
	if(CMAKE_GENERATOR STREQUAL "Visual Studio 10")
		SET(compiler "vc100")
	endif(CMAKE_GENERATOR STREQUAL "Visual Studio 10")
	 
    if(NOT compiler)
        SET(compiler "unknown")
    endif(NOT compiler)
endif(CMAKE_CXX_COMPILER MATCHES cl)
